### ISSUE TITLE
Ability to change the type of the primary key

### ISSUE THREAD

**Issue by kevinslin** [simonw/openai-to-sqlite#10]
This might be more of a question that an issue - is there a reason why the primary key is `text` vs a numeric datatype?
We're currently using this to generate embeddings for semantic search and store our primary keys for embeddings as `bigint` instead of `text`

**Comment by simonw** [comment]
That's so the mechanism works with both tables that use `text` primary keys and tables that use `integers` - I'm abusing `text` as an "any value goes" column.

**Comment by kevinslin** [comment]
makes sense. thanks for the update
